services:

  web:
    build: .

    command: gunicorn cafe.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - .:/app

    ports:
      - "8090:8000"

    depends_on:
      - db

    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:17

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_DB=cafe_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

volumes:
  postgres_data: